name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check some build related things
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git diff
          ls -la .
          git tag -l

###########################################################################################
      - name: test pre-commit
        id: pre-commit
        run: ./pre-commit-bash.sh
        env:
          token: wibble

